server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:~/zupbank
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, configprops, health, prometheus
  info:
    env:
      enabled: true
info:
  application:
    name: ZupBank
    description: Aplicação do Banco Digital da ZUP
